name: NPM Audit

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  npm-audit-check:
    name: Run `npm audit fix --dry-run`
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run npm audit fix --dry-run
        run: npm audit fix --dry-run
